ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  issuer: "https://127.0.0.1"
  domain: "https://127.0.0.1"
  audience: "users"
  realm: "dove drop project"